name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Extract repository name
        id: extract_repo
        run: echo "::set-output name=repo::${GITHUB_REPOSITORY##*/}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags:
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.extract_repo.outputs.repo
            }}:${{ steps.extract_version.outputs.version }}

      - name: Log out from Docker Hub
        run: docker logout
